"""initial

Revision ID: 243cbefcfa52
Revises: 
Create Date: 2026-03-09 21:35:50.349122

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '243cbefcfa52'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('error_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('service', sa.String(length=128), nullable=False),
    sa.Column('environment', sa.String(length=64), nullable=False),
    sa.Column('exception_type', sa.String(length=256), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('traceback', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('release', sa.String(length=128), nullable=True),
    sa.Column('user_id', sa.String(length=256), nullable=True),
    sa.Column('request_path', sa.String(length=512), nullable=True),
    sa.Column('request_method', sa.String(length=16), nullable=True),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_error_events_created_at', 'error_events', ['created_at'], unique=False)
    op.create_index('ix_error_events_fingerprint_service', 'error_events', ['fingerprint', 'service'], unique=False)
    op.create_table('issues',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('service', sa.String(length=128), nullable=False),
    sa.Column('environment', sa.String(length=64), nullable=False),
    sa.Column('exception_type', sa.String(length=256), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('occurrence_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_issues_fingerprint_service', 'issues', ['fingerprint', 'service'], unique=True)
    op.create_index('ix_issues_last_seen', 'issues', ['last_seen'], unique=False)
    op.create_index('ix_issues_service_status', 'issues', ['service', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_issues_service_status', table_name='issues')
    op.drop_index('ix_issues_last_seen', table_name='issues')
    op.drop_index('ix_issues_fingerprint_service', table_name='issues')
    op.drop_table('issues')
    op.drop_index('ix_error_events_fingerprint_service', table_name='error_events')
    op.drop_index('ix_error_events_created_at', table_name='error_events')
    op.drop_table('error_events')
    # ### end Alembic commands ###